---
title: "Untitled"
output: html_document
---

```{r}
df1.2 %>% 
  ggplot(aes(`計上～支払期限`)) +
  geom_histogram(aes(y =..density..), bins = 30)+
   stat_bin(aes(y=..density.., label=..count..), geom="text", vjust=-.5)+
  geom_line(aes(y = dgamma(`計上～支払期限`, shape = adj_shape, rate = adj_rate)), color = "red")

df1.2 %>% 
  ggplot(aes(`計上～支払期限`)) +
  geom_histogram(aes(y =..density..), binwidth = 16)+
   stat_bin(aes(y=..density.., label=..density..), binwidth = 16, geom="text", vjust=-.5)+
  geom_line(aes(y = dgamma(`計上～支払期限`, shape = adj_shape, rate = adj_rate)), color = "red")

df1.2 %>% 
  ggplot(aes(`計上～支払期限`)) +
  geom_histogram(aes(y =..density..), binwidth = 16, fill = "light blue")+
   stat_bin(aes(y=..density.., label=..density..), binwidth = 16, geom="text", hjust=1.8)+
  coord_flip()
```

```{r}
df1.2 %>% 
  ggplot()+
  geom_boxplot(aes(y = `計上～支払期限`))
```

```{r}
max(df1.2$`計上～支払期限`)/30
18%/%16
```
```{r}
df1.2 %>% 
  arrange(`計上～支払期限`) %>% 
  head(350)
```


```{r}
# data to density data
density1.2 <- df1.2 %>% 
  mutate(interval_id = (`計上～支払期限`+7)%/%16) %>% 
  group_by(interval_id) %>% 
  summarise(count = n()) %>% 
  mutate(middle_interval = 16*interval_id, 
         density = count/nrow(df1.2)/16)
        #density = count/sum(count)/binwidth
```

```{r}
nls1.2 <- nls(# 公式：ガンマ分布密度関数
              formula = density ~ dgamma(middle_interval, shape, rate),
              
              # データ：元データから計算された各ノードと確率密度データ
              data = density1.2,
              
              # スタート：最初にフィードするパラメタ
              start = list(shape = adj_shape,
                           rate = adj_rate)
              )

nls1.2_pred <- predict(nls1.2, density1.2)
```


```{r}
nls1.2
```

```{r}
density1.2 %>% mutate(gamma_pred = nls1.2_pred) %>% view()
```


```{r}
density1.2 %>% mutate(gamma_pred = nls1.2_pred) %T>% print() %>% 
  ggplot(aes())+
  geom_col(aes(x = middle_interval, y = density)) +
  geom_line(aes(x = middle_interval, y = gamma_pred), color = "#00BFC4")
  
df1.2 %>% 
  ggplot(aes(`計上～支払期限`)) +
  geom_histogram(aes(y =..density..), binwidth = 16, color = "white") +
  geom_line(aes(y = dgamma(`計上～支払期限`, shape = 6.8583 , rate = 0.1338)), color = "#F8766D")  
```


```{r}
?pgamma
?geom_vline
```

```{r}
qgamma(p = 0.975, 
       shape = 6.8583 , 
       rate = 0.1338)
```

```{r}
outlier_fill <- function(x) {
    y <- dgamma(x, shape = 6.8583 , rate = 0.1338)
    y[x < 96] <- NA
    return(y)
}

df1.2 %>% 
  ggplot(aes(`計上～支払期限`)) +
  # geom_histogram(aes(y =..density..), binwidth = 16, color = "white") +
  geom_line(aes(y = dgamma(`計上～支払期限`, shape = 6.8583 , rate = 0.1338)), color = "#F8766D") +
  geom_vline(aes(xintercept = qgamma(p = 0.975, shape = 6.8583 , rate = 0.1338))) +
  geom_text(aes(x= 90, label="上限2.5％閾値：96.14", y=0.01), colour="black", angle=90, vjust = 1.5, size=5) +
  stat_function(fun=outlier_fill, geom="area", fill="#ff2b00", alpha=1)
```

```{r}
df1.2 %>% 
  mutate(外れ値 = ifelse(
    `計上～支払期限` <= qgamma(p = 0.975, 
                               shape = 6.8583 , 
                               rate = 0.1338), 
                            FALSE, 
                            TRUE)
    ) %>% 
  group_by(外れ値) %>% 
  count() %>% 
  ungroup() %>% 
  mutate(比率 = round(n/sum(n), 3)) %>% view()
```

```{r}
959/(959+12976)
```


```{r}
df1.2 %>% 
  mutate(外れ値 = ifelse(`計上～支払期限` <= qgamma(p = 0.975, shape = 6.8583 , rate = 0.1338), 
                      FALSE, TRUE)) %>% 
  ggplot(aes(record_date, `計上～支払期限`, color = 外れ値)) +
  geom_jitter(alpha = .5) +
  scale_color_manual(values=c("#00BFC4","#F8766D"))+
  labs(y= "計上～支払期限", x = "計上日")
  
```

