---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(readxl)
library(magrittr)
```

```{r}
# input data
SUB_CONSOLI_CALCULATED_OUTPUT
MST_ACCOUNT_FORSUM_OUTPUT
```


```{r}
# 1. Account_Code_09 をキーとして、【SUB_CONSOLI_CALCULATED】に【MST_ACCOUNT_FORSUM】をinner joinし、Sum_Account_Code、Sum_Account_Nameを付加
SUB_CONSOLI_ADD_STEP1 <- SUB_CONSOLI_CALCULATED_OUTPUT %>% 
  left_join(MST_ACCOUNT_FORSUM_OUTPUT, by = "Account_Code_09") %>%
  select(YM,
		     主管部コード4桁,
		     Company_Code,
		     Flg_PLorBS,
		     Sum_Account_Code,
		     Sum_Account_Name,
		     Account_Code_09,
         P_Company_Code,
		     val) %>% 
  arrange(YM,
		     主管部コード4桁,
		     Company_Code,
		     Flg_PLorBS,
		     Sum_Account_Code,
		     Sum_Account_Name,
		     Account_Code_09)



# 2.Sum_Account_Codeごとに年度・会社別のvalを集計し、連結精算表にしか存在しない科目の値を算出
# 3.Rename：Sum_Account_Code → Account_Code ,　Sum_Account_Name → Account_Name
SUB_CONSOLI_ADD_STEP2 <- SUB_CONSOLI_ADD_STEP1 %>% 
  group_by(YM,
		       主管部コード4桁,
		       Company_Code,
		       Flg_PLorBS,
		       Sum_Account_Code,
		       Sum_Account_Name,
           P_Company_Code) %>%
  summarise(val = sum(val)) %>% 
  rename(Account_Code = Sum_Account_Code,
         Account_Name = Sum_Account_Name)




# 4. 算出科目【Sub_Consoli_Add】と【Sub_Consoli_Calculated】の両方に存在する科目があれば、【Sub_Consoli_Calculated】の科目を優先
# 4.1 YM, Company_Code, Account_Code をキーとして、上記までのデータに【Sub_Consoli_Calculated】をleft join し、【Sub_Consoli_Calculated】由来のAccount_CodeをAccount_Code_addとして格納
# 4.2 Account_Code_add <> NULLのレコードは削除（【Sub_Consoli_Calculated】の方に連結精算表科目コードと1対1対応する科目コードがあるため）

SUB_CONSOLI_ADD_OUTPUT <- SUB_CONSOLI_ADD_STEP2 %>% 
  left_join(SUB_CONSOLI_CALCULATED_OUTPUT %>% 
              mutate(Account_Code_add = Account_Code) %>% 
              select(YM, Company_Code, Account_Code, Account_Code_add),
            by = c("YM", "Company_Code", "Account_Code")) %>% 
  filter(is.na(Account_Code_add)) %>% 
  select(-Account_Code_add)
  
write_tsv(SUB_CONSOLI_ADD_OUTPUT, "10_SUB_CONSOLI_ADD.tsv") 
```



#==================test=============================

```{r}
SUB_CONSOLI_CALCULATED_OUTPUT %>% 
              mutate(Account_Code_add = Account_Code) %>% 
              select(YM, Company_Code, Account_Code, Account_Code_add)
```


```{r}
SUB_CONSOLI_ADD_STEP2 %>% 
  filter(YM == "201503", Company_Code =="A000049S")


```


```{r}
SUB_CONSOLI_ADD_OUTPUT %>% 
  filter(YM != "201903")
```

